apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolap-frontend
  labels:
    app: dolap-frontend
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: dolap-frontend
  template:
    metadata:
      labels:
        app: dolap-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 80
