replicaCount: 1

image:
  repository: firataydincak/dolap-backend
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 8000
  # 30000-32767 arasında boş bir port seçiyoruz. 
  # Frontend 30080 olduğu için bunu 30081 yapalım.
  nodePort: 30081

containerPort: 8000
