apiVersion: v1
kind: Service
metadata:
  name: {{ include "dolap-backend.fullname" . }}
  labels:
    app: {{ include "dolap-backend.fullname" . }}
spec:
  # Dışarıdan erişim için NodePort veya LoadBalancer yapabilirsin
  # Şimdilik ClusterIP kalsın, port-forward ile bağlanırız
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "dolap-backend.fullname" . }}
