# templates/job-new-replicaset-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-new-rs-check
  namespace: default
  labels:
    job-type: new-replicaset-check
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "5"
spec:
  ttlSecondsAfterFinished: 300
  completions: 1
  parallelism: 1
  backoffLimit: 2
  activeDeadlineSeconds: 30
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: flowe-pod-checker
      restartPolicy: Never
      containers:
      - name: check-new-rs
        image: alpine/kubectl:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "150m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "200Mi"
        command:
          - /bin/sh
          - -c
          - |
            set -eu

            echo "🔍 [NEW REPLICASET CHECK] Checking NEW pods for guestbook-ui..."
            APP_NAME="guestbook-ui"
            NAMESPACE="default"

            HPA_EXISTS=$(kubectl get hpa "$APP_NAME" -n "$NAMESPACE" --ignore-not-found)
            if [ -n "$HPA_EXISTS" ]; then
              MIN_REPLICAS=$(kubectl get hpa "$APP_NAME" -n "$NAMESPACE" -o jsonpath='{.spec.minReplicas}' 2>/dev/null)
              EXPECTED_READY=${MIN_REPLICAS:-2}
              echo "✅ HPA detected. Using minReplicas=$EXPECTED_READY"
            else
              DEPLOY_REPLICAS=$(kubectl get deploy "$APP_NAME" -n "$NAMESPACE" -o jsonpath='{.spec.replicas}' 2>/dev/null || echo "")
              DEPLOY_REPLICAS=${DEPLOY_REPLICAS:-0}
              if [ "$DEPLOY_REPLICAS" -ge 1 ] 2>/dev/null; then
                EXPECTED_READY=$DEPLOY_REPLICAS
              else
                EXPECTED_READY=2
              fi
            fi

            echo "📊 Expected ready pods in NEW ReplicaSet: $EXPECTED_READY"
            echo "🔎 Finding newest ReplicaSet..."

            NEWEST_RS=$(kubectl get rs -n "$NAMESPACE" -l app="$APP_NAME" \
              --sort-by=.metadata.creationTimestamp \
              -o jsonpath='{.items[-1:].metadata.name}')

            echo "✅ Newest ReplicaSet: $NEWEST_RS"

            RS_POD_TEMPLATE_HASH=$(kubectl get rs "$NEWEST_RS" -n "$NAMESPACE" \
              -o jsonpath='{.metadata.labels.pod-template-hash}')

            echo "✅ Pod template hash: $RS_POD_TEMPLATE_HASH"
            echo "⏱️ Starting monitoring (timeout: 40 minutes)..."
            echo "=========================================="

            START_TIME=$(date +%s)
            TIMEOUT=$((40 * 60))

            while true; do
              NOW=$(date +%s)
              ELAPSED=$(( NOW - START_TIME ))

              if [ "$ELAPSED" -ge "$TIMEOUT" ]; then
                echo "❌ TIMEOUT reached"
                exit 1
              fi

              READY_NEW=$(kubectl get pods -n "$NAMESPACE" \
                -l "app=$APP_NAME,pod-template-hash=$RS_POD_TEMPLATE_HASH" \
                -o jsonpath='{.items[*].status.containerStatuses[*].ready}' \
                | grep -o true | wc -l || true)

              TOTAL_NEW=$(kubectl get pods -n "$NAMESPACE" \
                -l "app=$APP_NAME,pod-template-hash=$RS_POD_TEMPLATE_HASH" \
                --no-headers | wc -l || true)

              READY_NEW=${READY_NEW:-0}
              TOTAL_NEW=${TOTAL_NEW:-0}

              ELAPSED_MIN=$(( ELAPSED / 60 ))
              ELAPSED_SEC=$(( ELAPSED % 60 ))

              if [ "$READY_NEW" -ge "$EXPECTED_READY" ] && [ "$EXPECTED_READY" -gt 0 ]; then
                echo "=========================================="
                echo "✅ SUCCESS! New ReplicaSet pods are ready"
                echo "   ReplicaSet: $NEWEST_RS"
                echo "   Ready pods: $READY_NEW / Expected: $EXPECTED_READY"
                echo "   Total new pods: $TOTAL_NEW"
                echo "   Time elapsed: ${ELAPSED_MIN}m ${ELAPSED_SEC}s"
                exit 0
              fi

              echo "⏳ [$ELAPSED_MIN:$ELAPSED_SEC] New RS: $NEWEST_RS | Ready: $READY_NEW/$EXPECTED_READY | Total new pods: $TOTAL_NEW"
              sleep 5
            done
