---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-checker
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-checker-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-checker-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-checker
  namespace: default
roleRef:
  kind: Role
  name: pod-checker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pod-readiness-check
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: pod-checker
      containers:
      - name: check-ready
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Checking pod readiness for guestbook-ui..."
          while true; do
            READY=$(kubectl get pods -n default -l app=guestbook-ui -o jsonpath='{.items[*].status.containerStatuses[*].ready}'| grep -o true)
            #TOTAL=$(kubectl get pods -n default -l app=guestbook-ui --no-headers | wc -l)
            EXPECTED_READY=2
            #if [ "$READY" -eq "$TOTAL" ] && [ "$TOTAL" -gt 0 ]; then
            if [ "$READY" -eq "$EXPECTED_READY" ] && [ "$EXPECTED_READY" -gt 0 ]; then
              echo "All guestbook-ui pods are ready"
              exit 0
            fi
            echo "Waiting for guestbook-ui pods to be ready..."
            sleep 5
          done
      restartPolicy: Never
  backoffLimit: 1
